### PR TITLE
Apply regex approach

### PR DESCRIPTION
**Pull request by aoki**
I have same problem(#17).
This PR is not configurable.

I use [pure](https://github.com/sindresorhus/pure) prompt.
It shows process name at the after `—` when I adopt regex instead of [atom/fuzzaldrin](https://github.com/atom/fuzzaldrin).
I think don't need fuzzy matching.

This regex `(?:[\W]+|^)(PROCESS_NAME)(?:[\W]+|$)` match below cases.
In this case PROCESS_NAME is 'foo'.

- 'user : ~/work/github foo'
- 'user : foo - ~/work/github'
- 'foo : user - ~/work/github'

```javascript
> const regex = /(?:[\W]+|^)(foo)(?:[\W]+|$)/
> regex.test('user : ~/work/github foo');
true
> regex.test('user : foo - ~/work/github');
true
> regex.test('foo : user - ~/work/github');
true
```

pr

Please close this PR If you don't need.

### CODE REVIEW

**Comment by dfrankland** [comment]
I like this for it's simplicity, but what if there's a process that's similar, but doesn't **_exactly_** match? I think it's nice if there's a way to match processes that are related, no? Although, fuzzy finding does't work that well either.

For example, `nodes` would get matched with `node` even though it's not explicitly listed in the icon classes array.

**Comment by henrikruscon** [comment]
Problem with this regex is that for example it'll also match with a folder namned node.

**Comment by dfrankland** [comment]
@henrikdahl good point.

**Comment by henrikruscon** [comment]
What about [this?](http://scriptular.com/#(%3F%3A%5B%5Cs%5D%2B%7C%5E)(node)(%3F%3A%5B%5CW%5D%2B%7C%24)%7C%7C%7C%7Ci%7C%7C%7C%7C%5B%22~%2Fprojects%2Fnode%22%2C%22~%2Fprojects%2Fnode%2Fresources%22%2C%22node%3A%20user%22%2C%22user%3A%20node%22%2C%22node%22%2C%22user%20-%20node%22%2C%22sites%3A%20cd%20node%22%5D)

It'll still flash the process icon though. When you cd node folder it'll change title for a millisecond to `sites: cd node` which matches.

**Comment by aoki** [comment]
It is a very difficult problem... 🤔
How to get process name position in a title using regex pattern (or fuzzy matching)..

One of the proposal, write config for the process position using regex.
However position eval and replacement for keyword too hard.
Not quite... 😢

**Comment by aoki** [comment]
We write config like a below.
`PROCESS_NAME` is process name position in a title.

```js
tabIcons: {
  processNameRegex: '(?:[\\W]+|^)PROCESS_NAME(?:[\\W]+|$)'
}
```

Load config and evaluate with `eval` (However, I don't like eval...).

```js
> var config = '(?:[\\W]+|^)PROCESS_NAME(?:[\\W]+|$)'
undefined
> var regexText = config.replace('PROCESS_NAME', '(${e})')
undefined
> regexText
"(?:[\W]+|^)(${e})(?:[\W]+|$)"
> eval(`var f = (e) => { return new RegExp(\`${regexText}\`, \'i\'); }`)
undefined
> f
(e) => { return new RegExp(`(?:[\W]+|^)(${e})(?:[\W]+|$)`, 'i'); }
> f('foo')
/(?:[W]+|^)(foo)(?:[W]+|$)/i
```

**Comment by jonaswindey** [comment]
Any chance of getting this merged?

**Comment by dfrankland** [comment]
This should be fixed with `hyper-tab-icons@1.1.3` now. See here: https://github.com/dfrankland/hyper-tab-icons#configtabiconsprocessnameregex

**Pull request closed without merging**
