### PR TITLE
Add new icons for compilation and monitoring

### PR DESCRIPTION
**Pull request by jbergstroem**
Not very proud of the sizing here. Did you (or someone else) perhaps adjust icon height to better fit the text-size in the svg? Other than that, I created two issues (#7, #8) I ran into while creating this PR.

### CODE REVIEW

**Comment by dfrankland** [comment]
Could you separate these into 2 pull-requests? It's hard to review otherwise. Thank you for your contribution! 😀

**Comment by jbergstroem** [comment]
Will do. I'll rebase on the git stuff.

Edit: done!

**Comment by jbergstroem** [comment]
ping!

**Comment by dfrankland** [comment]
pong! 👍

**Pull request merged**
