### PR TITLE
Icons for commonly used editors and viewers

### PR DESCRIPTION
**Pull request by trieloff**
- code (angle brackets icon) for pico, nano, micro editors
- read (maginying glass icon) for less, tail, more

### CODE REVIEW

**Comment by dfrankland** [comment]
Hello! Thanks for all the PRs 👍 Both `micro` and `nano` (`pico` by extension) have actual logos which I think would be better to differentiate the editors. What do you think of using those instead? As for the "read", I am not opposed to it considering `less`, `more`, and `tail` have no logos.

**Comment by trieloff** [comment]
Sounds good. I'll update when I have time.

**Comment by trieloff** [comment]
I've added icons for micro and nano, but left pico in place, as it does not have a real icon.

**Pull request merged**
